const demoData = [
  {
    id: "rpt_1",
    type: "Monthly",
    status: "Submitted",
    month: "May",
    year: "2026",
    submittedBy: "Demo Manager",
    dateSubmitted: "2026-05-31T10:00:00.000Z",
    startingFollowers: 1000,
    endingFollowers: 1250,
    totalAccountsReached: 15000,
    totalImpressions: 22000,
    totalReels: 12,
    totalPosts: 4,
    totalCarousels: 2,
    totalStories: 20,
    totalLikes: 800,
    totalComments: 120,
    totalShares: 300,
    totalSaves: 150,
    websiteClicks: 45,
    profileVisits: 300,
    whatsappClicks: 12,
    emailClicks: 2,
    callClicks: 5,
    topContent: [],
    demographics: {
      topCities: [],
      topCountries: [],
      ageDistribution: [],
      gender: { male: 0, female: 0, other: 0 },
      mostActiveDays: [],
      mostActiveHours: ""
    },
    categoryPerformance: [],
    biggestWin: "Started posting reels",
    biggestChallenge: "Consistency",
    contentToRepeat: "Reels",
    contentToStop: "Static posts",
    newIdeasToTest: "More carousels",
    lessonsLearned: "Keep trying",
    targetFollowers: 1500,
    targetEngagementRate: 5,
    targetReach: 20000,
    targetWebsiteClicks: 100,
    actionPlan: "Post more"
  },
  {
    id: "rpt_2",
    type: "Monthly",
    status: "Submitted",
    month: "June",
    year: "2026",
    submittedBy: "Demo Manager",
    dateSubmitted: "2026-06-30T10:00:00.000Z",
    startingFollowers: 1250,
    endingFollowers: 1800,
    totalAccountsReached: 28000,
    totalImpressions: 40000,
    totalReels: 15,
    totalPosts: 2,
    totalCarousels: 4,
    totalStories: 30,
    totalLikes: 1500,
    totalComments: 220,
    totalShares: 500,
    totalSaves: 350,
    websiteClicks: 85,
    profileVisits: 600,
    whatsappClicks: 25,
    emailClicks: 5,
    callClicks: 10,
    topContent: [],
    demographics: {
      topCities: [],
      topCountries: [],
      ageDistribution: [],
      gender: { male: 0, female: 0, other: 0 },
      mostActiveDays: [],
      mostActiveHours: ""
    },
    categoryPerformance: [],
    biggestWin: "Carousels are working!",
    biggestChallenge: "Time to edit",
    contentToRepeat: "Educational carousels",
    contentToStop: "",
    newIdeasToTest: "Collaborations",
    lessonsLearned: "Audience loves tips",
    targetFollowers: 2200,
    targetEngagementRate: 6,
    targetReach: 35000,
    targetWebsiteClicks: 150,
    actionPlan: "Collaborate with influencers"
  },
  {
    id: "rpt_3",
    type: "Monthly",
    status: "Submitted",
    month: "July",
    year: "2026",
    submittedBy: "Demo Manager",
    dateSubmitted: "2026-07-31T10:00:00.000Z",
    startingFollowers: 1800,
    endingFollowers: 2400,
    totalAccountsReached: 45000,
    totalImpressions: 65000,
    totalReels: 18,
    totalPosts: 0,
    totalCarousels: 8,
    totalStories: 45,
    totalLikes: 2800,
    totalComments: 340,
    totalShares: 900,
    totalSaves: 600,
    websiteClicks: 120,
    profileVisits: 900,
    whatsappClicks: 40,
    emailClicks: 8,
    callClicks: 15,
    topContent: [],
    demographics: {
      topCities: [],
      topCountries: [],
      ageDistribution: [],
      gender: { male: 0, female: 0, other: 0 },
      mostActiveDays: [],
      mostActiveHours: ""
    },
    categoryPerformance: [],
    biggestWin: "Hit 2k followers",
    biggestChallenge: "Reel views dropped",
    contentToRepeat: "High value carousels",
    contentToStop: "Trending audio reels",
    newIdeasToTest: "Talking head videos",
    lessonsLearned: "Quality over quantity",
    targetFollowers: 3000,
    targetEngagementRate: 7,
    targetReach: 55000,
    targetWebsiteClicks: 200,
    actionPlan: "Invest in good lighting"
  }
];

fetch("http://localhost:3000/api/admin/data", {
  method: "POST",
  headers: { "Content-Type": "application/json" },
  body: JSON.stringify({
    action: "updateClientResearch",
    data: {
      clientName: "Home Vista",
      filePath: "_AdvancedAnalytics.json",
      markdownContent: JSON.stringify(demoData)
    }
  })
}).then(res => res.json()).then(console.log).catch(console.error);
